apiVersion: v1
kind: Service
metadata:
  name: front

spec:
  selector:
    app: front

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort
  ---
apiVersion: v1
kind: Service
metadata:
  name: back

spec:
  selector:
    app: pback

  ports:
    - name: http
      port: 5000

  type: ClusterIP
